name: Set up project
description: Prepare the project in GitHub Actions

inputs:
  bun-version:
    description: Version of Bun to use
  
  pnpm-version:
    description: Version of pnpm to use

  node-version:
    description: Version of Node to use
    default: 24.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Bun
      if: ${{ inputs.bun-version }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: 🏗 Setup pnpm
      if: ${{ inputs.pnpm-version }}
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
