name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: ./setup-node
        with:
          node-version: '18'
          
      - name: Setup Expo
        uses: ./setup-expo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Build for release
        uses: ./build-app
        with:
          platform: 'all'
          profile: 'production'
          
      - name: Deploy to stores
        uses: ./deploy-app
        with:
          platform: 'all'
          submit: 'true'